package com.trunk.rx.json.impl;

public enum NumberState {
  NUMBER_CHAR_NONE,
  NUMBER_CHAR_SIGN,
  NUMBER_CHAR_DIGIT,
  NUMBER_CHAR_DECIMAL,
  NUMBER_CHAR_FRACTION_DIGIT,
  NUMBER_CHAR_EXP_E,
  NUMBER_CHAR_EXP_SIGN,
  NUMBER_CHAR_EXP_DIGIT,
}
